source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'RxAppState_Example', :exclusive => true do
  pod 'RxAppState', :path => '../'
end

target 'RxAppState_Tests', :exclusive => true do
  pod 'RxAppState', :path => '../'
end
