source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'RxAppState_Example' do
    pod 'RxAppState', :path => '../'
    pod 'RxSwift', '3.0.0-beta.2'
    pod 'RxCocoa', '3.0.0-beta.2'
    
    target 'RxAppState_ExampleTests' do
        inherit! :search_paths
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
